# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8e5751b2d50b603f578de5b50bd93318f6d90313b9e25b08c582bea29761a4c33454b1af3a6a4c4e679f11057393df14b8441e864e230958aa04e92105a6f39c

test:
  secret_key_base: d1b8bc38b5b3581523daacbd4be61d39b7aebfaece5e602ff0843f74986fc5f5e264b9bce86fd1b01f765060eaa49f67e802858be98f32117de13eaac9d0ab68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
